import { CardType } from "./card";

export const initPlayerDeck = [
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
];

export const initFoeDeck = [
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
    { type: CardType.Unit, name: "Bob" },
];